name: Regression Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build_Test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.5
      
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && chmod -R go= ~/.ssh && echo "{{ secrets.INNERSOURCE_IAC_KEY }}" >> ~/.ssh/authorized_keys && eval $(ssh-agent -s)
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.0

      - name: Install dependencies
        run: |
          cd test
          go get -v -t -d

      - name: Test
        run: |
          cd test
          go test -v 
